/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <gpio_driver.h>

//#if !defined(__SOFT_FP__) && defined(__ARM_FP)
//  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
//#endif
/********************************************************************************************************************
												User Defined Variable for LED
********************************************************************************************************************/
#define GPIOC_PIN_13	13
#define BLUE_LED 		GPIOC_PIN_13
#define GPIOA_PIN_0		0
#define GPIO_BUTTON_PIN	GPIOA_PIN_0

/********************************************************************************************************************
												User Defined Functions Declaration for LED
********************************************************************************************************************/

/**
	* @brief  Initialize the LEDs
	* @param  None
	* @retval None
*/
void led_init(void);

/**
	* @brief  Turns ON the led which is connected on the given pin
	* @param  *GPIOx : Base address of the GPIO Port
	* @param  Pin : pin number of the LED
	* @retval None
*/
void led_turn_on(GPIO_TypeDef *GPIOx, uint16_t pin);

/**
	* @brief  Turns OFF the led which is connected on the given pin
	* @param  *GPIOx : Base address of the GPIO Port
	* @param  Pin : pin number of the LED
	* @retval None
*/
void led_turn_off(GPIO_TypeDef *GPIOx, uint16_t pin);

/**
	* @brief  Toggels the led which is connected on the given pin
	* @param  *GPIOx : Base address of the GPIO Port
	* @param  Pin : pin number of the LED
	* @retval None
	*/
void led_toggle(GPIO_TypeDef *GPIOx, uint16_t pin);

int main(void)
{
    uint32_t i;
    led_init(); //Initialize teh LED

    //Enable the clock for GPIO Port A
    _HAL_RCC_GPIOA_CLK_ENABLE_RCC();

    //Configure Button Interrupt as Falling Edge
    hal_gpio_configure_interrupt(GPIO_BUTTON_PIN, INT_FALLING_EDGE);
    //Enable the Interrupt at EXTI0 Line
    hal_gpio_enable_interrupt(GPIO_BUTTON_PIN, EXTI0_IRQn);

#if 0
    while(1)
    {
    	led_turn_on(GPIOC, BLUE_LED);
    	for(i = 0; i < 50000; i++);

    	led_turn_off(GPIOC, BLUE_LED);
    	for(i = 0; i < 50000; i++);
    }
#endif

    while(1);


}

/********************************************************************************************************************
												User Defined Functions Definition for LED
********************************************************************************************************************/

/**
	* @brief  Initialize the LEDs
	* @param  None
	* @retval None
*/
void led_init(void)
{
	gpio_pin_conf_t led_pin_conf;
	//Enable the clock for GPIOC Port
	_HAL_RCC_GPIOC_CLK_ENABLE_RCC();

	led_pin_conf.pin = BLUE_LED;
	led_pin_conf.mode = GPIO_PIN_OUTPUT_MODE;
	led_pin_conf.op_type = GPIO_PIN_OP_TYPE_PUSHPULL;
	led_pin_conf.speed = GPIO_PIN_SPEED_MEDIUM;
	led_pin_conf.pupd = GPIO_PIN_NO_PULLUPPUSHDOWN;

	hal_gpio_init(GPIOC, &led_pin_conf);
}

/**
	* @brief  Turns ON the led which is connected on the given pin
	* @param  *GPIOx : Base address of the GPIO Port
	* @param  Pin : pin number of the LED
	* @retval None
	*/
void led_turn_on(GPIO_TypeDef *GPIOx, uint16_t pin)
{
	hal_gpio_write_to_pin(GPIOx, pin, 1);
}

/**
	* @brief  Turns OFF the led which is connected on the given pin
	* @param  *GPIOx : Base address of the GPIO Port
	* @param  Pin : pin number of the LED
	* @retval None
*/
void led_turn_off(GPIO_TypeDef *GPIOx, uint16_t pin)
{
	hal_gpio_write_to_pin(GPIOx, pin, 0);
}

/**
	* @brief  Toggels the led which is connected on the given pin
	* @param  *GPIOx : Base address of the GPIO Port
	* @param  Pin : pin number of the LED
	* @retval None
*/
void led_toggle(GPIO_TypeDef *GPIOx, uint16_t pin)
{
	if(hal_gpio_read_from_pin(GPIOx, pin))
		hal_gpio_write_to_pin(GPIOx, pin, 0);
	else
		hal_gpio_write_to_pin(GPIOx, pin, 1);
}

/**
	* @brief  ISR for the configured EXTI0 interrupt
	* @retval None
*/
void EXTI0_IRQHandler(void)
{
	hal_gpio_clear_interrupt(GPIO_BUTTON_PIN);
	/* Do your TASK here */
	led_toggle(GPIOD,BLUE_LED);
}















